#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
 path: /accueil
 controller: App\Controller\MonstreController::accueil
listeMonstre:
 path: /listeMonstre
 controller: App\Controller\MonstreController::afficherListeMonstre
ajouterMonstre:
 path: /ajouterMonstre
 controller: App\Controller\MonstreController::ajouterMonstre
modifierMonstre:
 path: /modifierMonstre/{id}
 controller: App\Controller\MonstreController::modifierMonstre
 requirements:
  id: \d+
 defaults :
  id: 1
voirMonstre:
 path: /voirMonstre/{id}
 controller: App\Controller\MonstreController::voirMonstre
 requirements:
  id: \d+
 defaults :
  id: 1
supprimerMonstre:
 path: /supprimerMonstre/{id}
 controller: App\Controller\MonstreController::supprimerMonstre
 requirements:
  id: \d+